# Generated by Django 5.1.6 on 2025-03-22 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tilan nimi')),
                ('capacity', models.IntegerField(verbose_name='Kapasiteetti')),
                ('location', models.CharField(max_length=100, verbose_name='Sijainti')),
                ('description', models.TextField(blank=True, verbose_name='Kuvaus')),
                ('equipment', models.TextField(blank=True, verbose_name='Varustelu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Käytössä')),
            ],
            options={
                'verbose_name': 'Tila',
                'verbose_name_plural': 'Tilat',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Alkamisaika')),
                ('end_time', models.DateTimeField(verbose_name='Päättymisaika')),
                ('purpose', models.TextField(verbose_name='Käyttötarkoitus')),
                ('status', models.CharField(choices=[('pending', 'Odottaa'), ('approved', 'Hyväksytty'), ('rejected', 'Hylätty'), ('cancelled', 'Peruutettu')], default='pending', max_length=20, verbose_name='Tila')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Käyttäjä')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.room', verbose_name='Tila')),
            ],
            options={
                'verbose_name': 'Varaus',
                'verbose_name_plural': 'Varaukset',
                'ordering': ['-start_time'],
            },
        ),
    ]
